config/routes.rb
Rails.application.routes.draw do

  get 'comments/index'

  get 'comments/new'

  get 'questions/index'

  get 'questions/new'

  get 'notifications/index'

  # get 'subjects/user:references'

  # devise_for :users,controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :users, :controllers => {:registrations => "registrations", sessions: 'sessions', omniauth_callbacks: 'omniauth_callbacks'}
  root to: "home#index"
  resources :subjects do
    resources :ratings, only: :update
  end
  resources :home, only: :index
  resources :donates
  resources :helps
  resources :surveys
  resources :calendars
  resources :assignments do
    resources :user_assignments
  end
  resources :notifications, only: :index
  resources :questions do
    resources :comments
  end

  get 'dashboard_page', to:'home#dashboard_page'
  get 'educator_dashboard', to:'home#educator_dashboard'
  get 'learner_dashboard', to:'home#learner_dashboard'
  get 'find_course', to:'helps#find_course'
  get 'message_to_instructor', to:'helps#message_to_instructor'
  get 'video_playback', to:'helps#video_playback'
  get 'failed_purchase', to:'helps#failed_purchase'
  get 'form', to:'donates#form'
  post 'form', to:'donates#form'
  post 'invoice', to:'donates#invoice'
  get 'video', to:'home#video'
  get 'about', to:'home#about'
  get 'users/:id/educator_courses', to:'subjects#educator_courses',  :as => :educator_courses
  get 'educator_video', to:'surveys#educator_video'
  get 'subjects/:id/about_page', to:'subjects#about_page', :as => :about_page
  get 'all_educator', to:'home#all_educator'
  get 'assignment/:id/download_file', to:'assignments#download_file',  :as => :download_file
  get 'user/:id/user_profile', to:'home#user_profile', :as => :user_profile
  get 'submitted_assignment', to:'assignments#submitted_assignment'

  resources :settings
  get 'change_locale', to:'settings#change_locale'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.role == "educator"
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  after_create_commit { notify }
  # belongs_to :subject
  belongs_to :user
  has_many :user_assignments
  mount_uploader :avatar, AvatarUploader

  private

  def notify
    Notification.create(event: "New Assignment")
  end
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :subject
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :subject
  belongs_to :user
end

app/models/donate.rb
class Donate < ApplicationRecord
  belongs_to :user
  enum amount_type: [:complete, :monthly]
  enum CreditCardType: [:Visa, :Maestro ]
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :performance
  belongs_to :user
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :subject
  belongs_to :performance  
end

app/models/help.rb
class Help < ApplicationRecord
  enum user_type: [:student, :educator]
  enum level_type: [:beginner, :intermediate, :advanced]
end

app/models/home.rb
class Home < ApplicationRecord
  def self.search(search)
    where("Title LIKE ? ","%#{search}%")
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  after_create_commit { NotificationBroadcastJob.perform_now(Notification.count)}
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :user
  has_one :course_progress
  has_many :grades
  has_one :feedback
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :subject
  belongs_to :user
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
  has_one :calendar
  has_one :grade
  has_one :course_progress
  has_many :discussions
  mount_uploader :avatar, AvatarUploader
  has_many :ratings

  def self.search(term)
    where("Name LIKE ? ","%#{term}%")
  end

  def average_rating
    ratings.sum(:score) / ratings.size
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # after_initialize :assign_default_role, :if => :new_record?
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2, :twitter]

  mount_uploader :avatar, AvatarUploader
  serialize :avatars, JSON
  has_many :subjects
  has_many :feedbacks
  has_one  :performance
  has_many :grades
  has_many :assignments
  has_many :user_assignments
  has_many :inverse_user_assignments, :class_name => "User", :foreign_key => "educator_id"
  has_many :discussions
  has_many :donates
  has_many :ratings
  has_many :surveys
  has_many :questions
  has_many :comments

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end
    user
  end

  def self.new_with_session(params, session)
   super.tap do |user|
     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
   end
  end

  def assign_default_role
    self.add_role(:learner) if self.roles.blank?
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:search]
      @subjects = Subject.search(params[:search]).order("created_at ASC")
    else  
      @subjects = Subject.all.order("created_at ASC")
    end
  end

  def show
  end

  def video
  end

  def about
  end

  def all_educator
    @educators = User.where(role: "educator")
  end

  def dashboard_page
  end

  def learner_dashboard
  end

  def educator_dashboard
  end

  def user_profile
    @user = User.find(params[:id])
  end
end

app/helpers/donates_helper.rb
module DonatesHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<!DOCTYPE>
<html>
<head>
<body>
  <p>

    3 Great Content Sites and What You Can Learn From Them

    As content marketing becomes more popular, marketers may be looking for inspiration or fresh ideas. They may be thinking to themselves:

    “How can I make this blog better?”

    “What gets people to share posts?”

    “What do other blogs do well that I can learn?”

    That’s why I’m writing this post. I’ve compiled a list of websites that produce great content, each of which has its own unique qualities. I’ll break them down and explain why they’re good and what you can take away.

    So whether you’re new to content marketing or have been involved in it for years, my goal for this blog post is that it will give you some ideas and inspiration.

    Now, let’s examine the best content sites and what we can all learn from them:
  </p>
</body>
</head>
</html>

app/views/home/all_educator.html.erb
<div class="post">
  <button><%= link_to "Post Question" , new_question_path%></button>
  <button><%= link_to "Previous Posted Questions" , questions_path %></button>
  <button><%= link_to "submit assignment/documents" %></button><br /><br />
</div>
<p>
  <% @educators.each do |educator| %>
    <%= link_to "#{educator.first_name}" "#{educator.last_name}", user_profile_path(educator.id) %><br />
    <%= educator.email %><br /><br /><br />
  <% end %>
</p>

<style type="text/css">
  .post{
    text-align: center;
    margin: 10px;
  }
</style>

app/views/home/dashboard_page.html.erb
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="/subjects">Join Class</a>
  </li>
  <% if can? :create, @subject %>
    <li class="nav-item">
      <a class="nav-link" href="/surveys/new">Create Class</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/educator_dashboard">Educator Tab</a>
    </li>
  <% else %>
    <li class="nav-item">
      <a class="nav-link disabled" href="#">Create Class</a>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" href="#">Educator Tab</a>
    </li>
  <% end %>
  <li class="nav-item">
    <a class="nav-link" href="/learner_dashboard">Learner Tab</a>
  </li>
  <li class="nav-item">
    <%= link_to image_tag('/notification-circle.png', size: "40x40"),notifications_path %>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/home">Main Page</a>
  </li>

  <li class="nav-item">
    <a href="/subjects" class="dropdown-toggle " data-toggle="dropdown">Menu</b></a>
    <ul id="dropdown-menu" class="dropdown-menu">
      <li><a href="/users/edit">Profile</a></li>
      <li><a href="/helps/new">Help</a></li>
      <li><a href="/surveys/new">Create Class</a></li>
      <li><a href="#">Settings</a></li>
      <li><a href="/subjects">Join Class</a></li>
    </ul>
  </li>
</ul>

app/views/home/educator_dashboard.html.erb
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="/subjects">Create Class</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/subjects">Courses and Page</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Analytics</a>
  </li>
  <li class="nav-item">
    <a href="/subjects" class="dropdown-toggle " data-toggle="dropdown">Menu</b></a>
    <ul id="dropdown-menu" class="dropdown-menu">
      <li><a href="/users/edit">Profile</a></li>
      <li><a href="/helps/new">Help</a></li>
      <li><a href="/surveys/new">Create Class</a></li>
      <li><a href="#">Settings</a></li>
      <li><a href="/subjects">Join Class</a></li>
    </ul>
  </li>
</ul>

app/views/home/index.html.erb
<div>
  <%= image_tag('/gandhi1.jpg', size: "310x200") %>
  <%= image_tag('/mark-twain.jpg', size: "320x200") %>
  <%= image_tag('/nelson-mandelo.jpg', size: "320x200") %>
  <%= image_tag('/malcolm.jpg', size: "320x200") %>
</div><br />

<% if signed_in? %>
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link active" href="/dashboard_page">Dashboard Page</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/assignments">Assignment Page</a>
    </li>
    <% if current_user.role == "tutor_assistant" %>
    <li class="nav-item">
      <a class="nav-link" href="/all_educator">Tutor/Teaching Assignment Page</a>
    </li>
      <li class="nav-item">
        <a class="nav-link active" href="/questions/new">Post Question</a>
        <%#= link_to "Post Question" , new_question_path%>
      </li>
    <% end %>
    <% if current_user.role == "tutor_assistant" || current_user.role == "educator" %>

      <li class="nav-item">
        <a class="nav-link active" href="/questions">Posted Questions</a>
        <%#= link_to "Previous Posted Questions" , questions_path %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/home/learner_dashboard.html.erb
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="/subjects">Join Class</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/subjects">My Courses</a>
  </li>
  <li class="nav-item">
    <%= link_to image_tag('/notification-circle.png', size: "40x40"),notifications_path %>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">My Performance</a>
  </li>
  <li class="nav-item">
    <a href="/subjects" class="dropdown-toggle " data-toggle="dropdown">Menu</b></a>
    <ul id="dropdown-menu" class="dropdown-menu">
      <li><a href="/users/edit">Profile</a></li>
      <li><a href="/helps/new">Help</a></li>
      <li><a href="/surveys/new">Create Class</a></li>
      <li><a href="#">Settings</a></li>
      <li><a href="/subjects">Join Class</a></li>
    </ul>
  </li>
</ul>

app/views/home/user_profile.html.erb
<html lang="en">
<head>      
  <body>  
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-sm-6">
          <div class="card hovercard">
          <div class="cardheader"></div>
            <div class="avatar">
              <% if current_user.avatar.present? %> 
                <%= image_tag current_user.avatar_url(:thumb) %>
                  <% else %>
                    
                <% end %>
            </div>
            <div>
              Name:-<%= @user.first_name.capitalize %>&nbsp;<%= @user.last_name.capitalize %><br>
              Email:-<%= @user.email%><br>
              Role:-<%= @user.role.capitalize %><br>
              Age:-<%= @user.age %><br>
              Level Of Education:-<%= @user.level_of_education %><br>
              Concentration:-<%= @user.concentration %><br>
              Institution_of_Education:-<%= @user.institution_of_education %><br>
              Location:-<%= @user.location %><br>
              Race:-<%= @user.race %><br>
              Employment_Status:-<%= @user.employment_status %><br>
              User_name:-<%= @user.username %><br>
              Bio:-<%= @user.bio %><br>
            </div>
          </div>
        </div>
      </div>
      <% if @user == current_user %>
        <div class="field" >
          <%= link_to "Update", edit_user_registration_path %>|
          <%= link_to "Back", :back %>
        </div> 
      <% end %>
    </div>
  </body>
</head>
</html>


<!-- <style type="text/css">
  .card {
    padding-top: 20px;
    margin: 10px 0 20px 0;
    background-color: rgba(214, 224, 226, 0.2);
    border-top-width: 0;
    border-bottom-width: 2px;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}

.card .card-heading {
    padding: 0 20px;
    margin: 0;
}

.card .card-heading.simple {
    font-size: 20px;
    font-weight: 300;
    color: #777;
    border-bottom: 1px solid #e5e5e5;
}

.card .card-heading.image img {
    display: inline-block;
    width: 46px;
    height: 46px;
    margin-right: 15px;
    vertical-align: top;
    border: 0;
    -webkit-border-radius: 70%;
    -moz-border-radius: 50%;
    border-radius: 60%;
}

.card .card-heading.image .card-heading-header {
    display: inline-block;
    vertical-align: top;
}

.card .card-heading.image .card-heading-header h3 {
    margin: 0;
    font-size: 14px;
    line-height: 16px;
    color: #262626;
}

.card .card-heading.image .card-heading-header span {
    font-size: 12px;
    color: #999999;
}

.card .card-body {
    padding: 0 20px;
    margin-top: 20px;
}

.card .card-media {
    padding: 0 20px;
    margin: 0 -14px;
}

.card .card-media img {
    max-width: 100%;
    max-height: 100%;
}

.card .card-actions {
    min-height: 30px;
    padding: 0 20px 20px 20px;
    margin: 20px 0 0 0;
}

.card .card-comments {
    padding: 20px;
    margin: 0;
    background-color: #f8f8f8;
}

.card .card-comments .comments-collapse-toggle {
    padding: 0;
    margin: 0 20px 12px 20px;
}

.card .card-comments .comments-collapse-toggle a,
.card .card-comments .comments-collapse-toggle span {
    padding-right: 5px;
    overflow: hidden;
    font-size: 12px;
    color: #999;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.card-comments .media-heading {
    font-size: 13px;
    font-weight: bold;
}

.card.people {
    position: relative;
    display: inline-block;
    width: 170px;
    height: 300px;
    padding-top: 0;
    margin-left: 20px;
    overflow: hidden;
    vertical-align: top;
}

.card.people:first-child {
    margin-left: 0;
}

.card.people .card-top {
    position: absolute;
    top: 0;
    left: 0;
    display: inline-block;
    width: 170px;
    height: 150px;
    background-color: #ffffff;
  }
</style> -->

app/views/home/video.html.erb
<div>
  <%= video_tag("/rails.mp4", size: "320x200", :controls => true) %>
</div>
<%= link_to "SKIP",subjects_path %>