config/routes.rb
Rails.application.routes.draw do

  get 'comments/index'

  get 'comments/new'

  get 'questions/index'

  get 'questions/new'

  get 'notifications/index'

  # get 'subjects/user:references'

  # devise_for :users,controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :users, :controllers => {:registrations => "registrations", sessions: 'sessions', omniauth_callbacks: 'omniauth_callbacks'}
  root to: "home#index"
  resources :subjects do
    resources :ratings, only: :update
  end
  resources :home, only: :index
  resources :donates
  resources :helps
  resources :surveys
  resources :calendars
  resources :assignments do
    resources :user_assignments
  end
  resources :notifications, only: :index
  resources :questions do
    resources :comments
  end

  get 'dashboard_page', to:'home#dashboard_page'
  get 'educator_dashboard', to:'home#educator_dashboard'
  get 'learner_dashboard', to:'home#learner_dashboard'
  get 'find_course', to:'helps#find_course'
  get 'message_to_instructor', to:'helps#message_to_instructor'
  get 'video_playback', to:'helps#video_playback'
  get 'failed_purchase', to:'helps#failed_purchase'
  get 'form', to:'donates#form'
  post 'form', to:'donates#form'
  post 'invoice', to:'donates#invoice'
  get 'video', to:'home#video'
  get 'about', to:'home#about'
  get 'users/:id/educator_courses', to:'subjects#educator_courses',  :as => :educator_courses
  get 'educator_video', to:'surveys#educator_video'
  get 'subjects/:id/about_page', to:'subjects#about_page', :as => :about_page
  get 'all_educator', to:'home#all_educator'
  get 'assignment/:id/download_file', to:'assignments#download_file',  :as => :download_file
  get 'user/:id/user_profile', to:'home#user_profile', :as => :user_profile
  get 'submitted_assignment', to:'assignments#submitted_assignment'

  resources :settings
  get 'change_locale', to:'settings#change_locale'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.role == "educator"
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  after_create_commit { notify }
  # belongs_to :subject
  belongs_to :user
  has_many :user_assignments
  mount_uploader :avatar, AvatarUploader

  private

  def notify
    Notification.create(event: "New Assignment")
  end
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :subject
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :subject
  belongs_to :user
end

app/models/donate.rb
class Donate < ApplicationRecord
  belongs_to :user
  enum amount_type: [:complete, :monthly]
  enum CreditCardType: [:Visa, :Maestro ]
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :performance
  belongs_to :user
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :subject
  belongs_to :performance  
end

app/models/help.rb
class Help < ApplicationRecord
  enum user_type: [:student, :educator]
  enum level_type: [:beginner, :intermediate, :advanced]
end

app/models/home.rb
class Home < ApplicationRecord
  def self.search(search)
    where("Title LIKE ? ","%#{search}%")
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  after_create_commit { NotificationBroadcastJob.perform_now(Notification.count)}
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :user
  has_one :course_progress
  has_many :grades
  has_one :feedback
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :subject
  belongs_to :user
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
  has_one :calendar
  has_one :grade
  has_one :course_progress
  has_many :discussions
  mount_uploader :avatar, AvatarUploader
  has_many :ratings

  def self.search(term)
    where("Name LIKE ? ","%#{term}%")
  end

  def average_rating
    ratings.sum(:score) / ratings.size
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # after_initialize :assign_default_role, :if => :new_record?
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2, :twitter]

  mount_uploader :avatar, AvatarUploader
  serialize :avatars, JSON
  has_many :subjects
  has_many :feedbacks
  has_one  :performance
  has_many :grades
  has_many :assignments
  has_many :user_assignments
  has_many :inverse_user_assignments, :class_name => "User", :foreign_key => "educator_id"
  has_many :discussions
  has_many :donates
  has_many :ratings
  has_many :surveys
  has_many :questions
  has_many :comments

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end
    user
  end

  def self.new_with_session(params, session)
   super.tap do |user|
     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
   end
  end

  def assign_default_role
    self.add_role(:learner) if self.roles.blank?
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  def index
  end

  def new
    @help = Help.new
  end

  def create
    @help = Help.new(helo_params)
    @help.save
  end

  def find_course
  end
  
  def message_to_instructor
  end

  def video_playback
  end

  def failed_purchase
  end

  private

  def helo_params
    params.require(:help).permit(:user_type, :learn, :level_type, :goal, :email, :description, :avatar)
  end
end

app/helpers/donates_helper.rb
module DonatesHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/helps/failed1.html.erb
<br> <h2> Неудачные покупки курса </h2> <br />
<p> У вас возникли проблемы с покупкой? Попытки покупок могут потерпеть неудачу по разным причинам: пожалуйста, взгляните на некоторые из наиболее распространенных проблем, которые могут возникнуть при попытке совершить покупку у Удмени. </p> <br />
<h4> Общие шаги по устранению неполадок для неудачных платежей </h4> <br />
<h5> Сохраненный способ оплаты </h5> <br />
<p> Вы пытаетесь приобрести с сохраненным способом оплаты? В качестве начального шага попробуйте удалить его и повторно добавить его, чтобы убедиться, что данные верны и обновлены. Для получения дополнительной информации о том, как это сделать, обратитесь к этой статье. Вы также можете удалить его из своего профиля Udemy, нажав здесь.
</p> <br />
<h5> Неполное имя </h5>
<p> Пожалуйста, убедитесь, что вы вводите свое имя и фамилию точно так же, как оно отображается на вашей карте в поле «имя на карте», или покупка может быть отклонена.
</p> <br />
<h5> Дебетовые карты, не относящиеся к США </h5> <br />
<p> Udemy базируется в Соединенных Штатах. Дебетовые карты в некоторых странах могут не разрешать иностранные транзакции. Если вы пытаетесь приобрести дебетовую карту, выпущенную за пределами США, и у вас возникли проблемы с внесением платежа, попробуйте позвонить в ваш банк, чтобы убедиться, что он уполномочен на международные покупки.
</p> <br />
<h5> Международные покупки </ h5> <br />
<p> Является ли страна-эмитент вашей карты отличной от вашей страны проживания? Если это так, ваша карта может быть не одобрена. Если у вас возникли проблемы с использованием карты, свяжитесь с Udemy Support, и мы можем изучить это для вас.
</p>

app/views/helps/failed_purchase.html.erb
<br><h2><%= t('helps.Failed Course Purchases') %></h2><br />
<p>Having trouble completing a purchase?  Purchase attempts can fail for a variety of reasons: please have a look at some of the most common issues that can happen, when attempting to make a purchase on Udemy.</p><br />
<h4>Common Troubleshooting Steps for Failed Payments </h4><br />
<h5>Saved Payment Method</h5><br />
<p>Are you trying to purchase with a saved payment method?  As an initial step, try deleting it and re-adding it to ensure the details are correct and up to date.  For more information about how to do this, please refer to this article.  You can also remove it from your Udemy profile by clicking here.
</p><br />
<h5>Incomplete Name</h5>
<p>Please ensure you are entering your first and last name exactly as it appears on your card in the “name on card” field, or the purchase may be declined.
</p><br />
<h5>Non-United States Debit Cards</h5><br />
<p>Udemy is based in the United States. Debit cards in some countries might not allow foreign transactions. If you’re trying to purchase with a debit card that was issued outside of the U.S., and you are experiencing trouble making a payment, try calling your bank to ensure it’s authorized for international purchases.
</p><br />
<h5>International Purchases</h5><br />
<p>Is the issuing country for your card different from your country of residence? If so, your card might not be approved. If you experience trouble using the card, contact Udemy Support and we can look into this for you.
</p>

app/views/helps/find_course.html.erb
<br><h2><%= t('helps.I Cant Find my Course') %></h2>
<p>If you've bought a course and it is not showing up in My Courses, try the following suggestions:</p>
<p>
  Is the Course Archived?
</p>
  <p>1.Go to My Courses.</p>
  <p>2. From the Categories filter on the left, select Archived </p>
  <p>3.If you see the missing course, click the ellipsis (...) and Unarchive the course.
  </p>
<h4>Missing Mobile Purchase</h4>
<p>If you purchased a course on mobile, it's possible that the course was not registered to your account. Please email your purchase receipt to support@udemy.com.</p>
<h4>Multiple E-mail Accounts</h4>
<p>If you use multiple e-mail accounts, or have a Facebook or Google account, try logging in with the associated e-mail addresses.</p>
<h4>Misspelled E-mail</h4>
<p>If you're still having trouble, you may have misspelled your e-mail when first signing up. If you did not receive an e-mail with a receipt for your purchase, please send a message to support@udemy.com and include your first and last name, and the title of the course that you're missing.</p>
<h4>Still Stuck?</h4>
<p>1.Course title</p>
<p>2.First and last name</p>
<p>3.Course purchase date</p>
<p>4.Purchase receipt</p>

app/views/helps/find_course1.html.erb
<br> <h2> Я не могу найти свой курс </h2>
<p> Если вы купили курс, и он не отображается в «Мои курсы», попробуйте следующие предложения: </p>
<p>
  Является ли курс архивированным?
</p>
  <p> 1.Покупайте мои курсы. </p>
  <p> 2. Из фильтра «Категории» слева выберите «Архивированный» </p>
  <p> 3. Если вы видите недостающий курс, щелкните эллипсис (...) и отпустите курс.
  </p>
<h4> Отсутствует мобильная покупка </h4>
<p> Если вы приобрели курс на мобильном телефоне, возможно, что курс не был зарегистрирован в вашей учетной записи. Отправьте рассылку по электронной почте на адрес support@udemy.com. </p>
<h4> Несколько учетных записей электронной почты </h4>
<p> Если вы используете несколько учетных записей электронной почты или имеете учетную запись Facebook или Google, попробуйте войти в систему с соответствующими адресами электронной почты. </p>
<h4> Письмо с ошибкой </h4>
<p> Если у вас все еще есть проблемы, у вас может возникнуть ошибка при отправке электронной почты при первой регистрации. Если вы не получили электронное письмо с квитанцией о покупке, отправьте сообщение на адрес support@udemy.com и укажите свое имя и фамилию и заголовок курса, который вам не хватает. </p>
<h4> Все еще застрял? </h4>
<p> 1. Название курса </p>
<p> 2. Имя и фамилия </p>
<p> Дата покупки на курсе </p>
<p> 4. Получение покупки </p>

app/views/helps/index.html.erb
<h1>Help#index</h1>
<p>Find me in app/views/help/index.html.erb</p>

app/views/helps/message_to_instructor.html.erb
<br><h2><%= t('helps.Send a Message to the Instructor')%></h2>
<p>Udemy instructors work hard to provide you with a high quality and compelling course. If you have any questions or comments about the course materials you can send the instructor a message. Please note: messaging is not yet available on the Udemy app.</p><br />
<h4>If You're Already Enrolled in the Course</h4><br>
<p>You can message an instructor from the course dashboard: </p>
<p>1. From My Courses, navigate to the course dashboard </p>
<p>2. On the left hand side of the page, click on Overview, and scroll down. You will see the instructor's profile at the bottom of the page. Click on the instructor's name and you will be directed to their profile page</p>
<p>3. Hit Send message. You will be taken to your inbox</p>
<p>4. Compose message and click Send</p><br />
<h4>If You're Not Enrolled in the Course</h4>
<p>​1. If you're browsing courses and want to ask a question before you enroll, send the instructor a question from the course landing page.</p>
<p>2. Scroll down to the About the Instructor section on the course landing page</p>
<p>3. Click on the instructor's name and you will directed to the their profile</p>
<p>4. Click on Send Message</p>
<p>5. Type your message and hit Send</p>

app/views/helps/message_to_instructor1.html.erb
<br> <h2> Отправить сообщение инструктору </h2>
<p> преподаватели Udemy упорно работать, чтобы предоставить вам с высоким качеством и убедительным, конечно. Если у вас есть какие-либо вопросы или комментарии о материалах курса, вы можете отправить инструктору сообщение. Обратите внимание: обмен сообщениями еще не доступен в приложении Udemy. </p> <br />
<h4> Если вы уже зарегистрированы на курсе </h4> <br>
<p> Вы можете отправить инструктора из панели курса: </p>
<p> 1. В разделе «Мои курсы» перейдите к панели управления курсом </p>
<p> 2. В левой части страницы нажмите Обзор и прокрутите вниз. Вы увидите профиль преподавателя в нижней части страницы. Нажмите на имя инструктора, и вы попадете на страницу своего профиля. </p>
<p> 3. Хит Отправить сообщение. Вы попадете в папку «Входящие» </p>
<p> 4. Напишите сообщение и нажмите «Отправить» </p> <br />
<h4> Если вы не зарегистрированы в курсе </h4>
<p> 1. Если вы просматриваете курсы и хотите задать вопрос перед тем, как зарегистрироваться, отправьте инструктору вопрос с целевой страницы курса. </p>
<Р> 2. Прокрутите вниз до раздела «О инструкторе» на целевой странице курса </p>
<p> 3. Нажмите на имя инструктора, и вы направите его профиль </p>
<p> 4. Нажмите «Отправить сообщение» </p>
<p> 5. Введите ваше сообщение и нажмите Отправить </p> <br>
<h2> Отправить сообщение инструктору </h2>

app/views/helps/new.html.erb
<%= form_for @help do |f| %>
  <div>
    <%= image_tag ('/maxresdefault.jpg'), size: "1210x300" %>
  </div><br><br />

  <table class="table table-bordered">
  <thead>
    <tr>
      <div class="btn-group btn-group-lg" role="group">

        <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#student" aria-expanded="false" aria-controls="footwear">Student
        </button>
        <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#educator" aria-expanded="false" aria-controls="footwear">Educator
        </button>
      </div>
    </tr>
  </thead>
  </table>
  <div id="student">
  <h2>Frequently Asked Questions</h2>
  <%= link_to "unable to find my course", find_course_path %><br>
  <%= link_to "send a message to the instructor", message_to_instructor_path %><br>
  <%= link_to "video playback issue", video_playback_path %><br>
  <%= link_to "failed course purchase", failed_purchase_path %><br>
  </div><br />

  <div id="educator">
  <h2>Frequently Asked Questions</h2>
  <%= link_to "why won't my video upload", find_course_path %><br>
  <%= link_to "Become a premium instructor and charge for course", message_to_instructor_path %><br>
  <%= link_to "video playback issues", video_playback_path %><br>
  <%= link_to "instructor revenue share", failed_purchase_path %><br>
  </div><br />

  <p>
    <%= f.label :user_type, "I am a..." %><br> 
    <%= f.select :user_type, Help.user_types.keys %>
  <p>
  <p>
    <%= f.label :learn, "what are you looking to learn?" %><br>
    <%= f.text_field :learn %>
  </p>
  <p>
    <%= f.label :level_type, "what is your current skill level?" %><br>
    <%= f.select :level_type, Help.level_types.keys %>
  <p>
  <p>
    <%= f.label :goal, "what is your goal? Why are you learning this?" %><br>
    <%= f.text_field :goal %>
  </p>
  <p>
    <%= f.label :email, "your email address*" %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :description, "Description*" %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :avatar, "Attachments" %><br>
    <%= f.file_field :avatar %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/helps/video_playback.html.erb
<br><h2><%= t('helps.Video Playback Issues') %></h2><br />
<p>If the video lecture is not loading, try the following steps to resolve the most common video loading issues.</p>
<h4>Troubleshooting</h4>
<p>1. Refresh your browser.</p>
<p>2. Quit your browser and re-open it.</p>
<p>3. Log out of Udemy and log back in.</p>
<p>4. Clear your browser's cookies and cache. Be sure to restart your browser before trying again.</p>
<p>5. Restart your computer and your modem</p>
<p>6. Check your browser version and update if outdated.</p>
<p>7. Try a different browser, like Google Chrome.</p>
<p>8. Try a different device or computer if possible</p>
<p>9. Turn off hardware acceleration (in Firefox or on Windows).</p>
<p>10. Try lowering the video quality of the lecture.</p>
<p>11. Take a note of your browser extensions/plugins/firewall programs. Is there anything that could be interfering with the streaming of the videos? We recommend testing with an incognito window to troubleshoot.</p>
<p>Test your internet connection's speed.</p><br />
<p>If you're still having trouble, it's possible that there's something wrong with the video file. Please send a message to the instructor and contact Udemy Support. When contacting support, please include:
</p><br />
<p>1. Your browser version</p>
<p>2. Your OS (Windows 7, Mac OS X, etc.)</p>
<p>3. The course URL and lecture number</p>
<p>4. Your internet connection speed test results</p>
<p>5. The resolution you were watching the video lecture at (ie - 720p, 480p etc)</p>
<p>6. A screenshot or screencast of the problem. The more information you can provide, the faster we'll be able to resolve the issues you're encountering on our site.</p><br />
<h5>Please note:</h5><p>currently the operating system for Chromebook machines are not fully supported by our video player. If you encounter video playback issues while using a Chromebook, and none of the troubleshooting steps above resolve the problem, please contact our support team. They will do their best to resolve the issue for you.</p><br />

app/views/helps/video_playback1.html.erb
<br> <h2> Пpоблемы с воспpоизведением видео </ h2> <br />
<p> Если видео лекция не загpужается, попpобуйте выполнить следующие шаги для pешения наиболее pаспpостpаненных пpоблем с загpузкой видео. </p>
<H4> Устpанение неполадок </ h4>
<p> 1. Обновите свой бpаузеp. </p>
<p> 2. Выйдите из бpаузеpа и откpойте его. </p>
<p> 3. Выйдите из Udemy и войдите в систему. </p>
<p> 4. Очистите файлы cookie и кеш бpаузеpа. Пеpед повтоpным попыткой пеpезагpузите бpаузеp. </p>
<p> 5. Пеpезагpузите компьютеp и модем </p>
<p> 6. Пpовеpьте веpсию своего бpаузеpа и обновите его, если устаpели. </p>
<p> 7. Попpобуйте использовать дpугой бpаузеp, напpимеp Google Chrome. </p>
<p> 8. Попpобуйте дpугое устpойство или компьютеp, если возможно </p>
<p> 9. Отключите аппаpатное ускоpение (в Firefox или в Windows). </p>
<p> 10. Попpобуйте снизить качество видео на лекции. </p>
<p> 11. Обpатите внимание на pасшиpения бpаузеpа / плагины / бpандмауэpы. Есть ли что-то, что может помешать потоковой пеpедаче видео? Мы pекомендуем пpоводить тестиpование с помощью окна инкогнито для устpанения неполадок. </p>
<p> Пpовеpьте скоpость вашего интеpнет-соединения. </p> <br />
<p> Если у вас все еще есть пpоблемы, возможно, что что-то не так с видео-файлом. Пожалуйста, отпpавьте сообщение инстpуктоpу и обpатитесь в службу поддеpжки Udemy. Пpи обpащении в службу поддеpжки пpосьба указать:
</p> <br />
<p> 1. Ваша веpсия бpаузеpа </p>
<p> 2. Ваша ОС (Windows 7, Mac OS X и т. Д.) </p>
<p> 3. URL куpса и номеp лекции </p>
<p> 4. pезультаты теста скоpости интеpнет-соединения </p>
<p> 5. pазpешение, на котоpое вы смотpели видео-лекцию (т.е. - 720p, 480p и т. Д.) </p>
<p> 6. Скpиншот или скpиншот пpоблемы. Чем больше инфоpмации вы можете пpедоставить, тем быстpее мы сможем pешить пpоблемы, с котоpыми вы сталкиваетесь на нашем сайте. </p> <br />
<h5> Обpатите внимание: </ h5> <p> в настоящее вpемя опеpационная система для устpойств Chromebook не полностью поддеpживается нашим видеоплееpом. Если вы столкнулись с пpоблемами воспpоизведения видео пpи использовании Chromebook, и ни одно из вышепеpечисленных шагов устpанения неполадок не pешит пpоблему, обpатитесь в нашу службу поддеpжки. Они сделают все возможное, чтобы pешить пpоблему для вас. </p> <br />