config/routes.rb
Rails.application.routes.draw do

  get 'comments/index'

  get 'comments/new'

  get 'questions/index'

  get 'questions/new'

  get 'notifications/index'

  # get 'subjects/user:references'

  # devise_for :users,controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :users, :controllers => {:registrations => "registrations", sessions: 'sessions', omniauth_callbacks: 'omniauth_callbacks'}
  root to: "home#index"
  resources :subjects do
    resources :ratings, only: :update
  end
  resources :home, only: :index
  resources :donates
  resources :helps
  resources :surveys
  resources :calendars
  resources :assignments do
    resources :user_assignments
  end
  resources :notifications, only: :index
  resources :questions do
    resources :comments
  end

  get 'dashboard_page', to:'home#dashboard_page'
  get 'educator_dashboard', to:'home#educator_dashboard'
  get 'learner_dashboard', to:'home#learner_dashboard'
  get 'find_course', to:'helps#find_course'
  get 'message_to_instructor', to:'helps#message_to_instructor'
  get 'video_playback', to:'helps#video_playback'
  get 'failed_purchase', to:'helps#failed_purchase'
  get 'form', to:'donates#form'
  post 'form', to:'donates#form'
  post 'invoice', to:'donates#invoice'
  get 'video', to:'home#video'
  get 'about', to:'home#about'
  get 'users/:id/educator_courses', to:'subjects#educator_courses',  :as => :educator_courses
  get 'educator_video', to:'surveys#educator_video'
  get 'subjects/:id/about_page', to:'subjects#about_page', :as => :about_page
  get 'all_educator', to:'home#all_educator'
  get 'assignment/:id/download_file', to:'assignments#download_file',  :as => :download_file
  get 'user/:id/user_profile', to:'home#user_profile', :as => :user_profile
  get 'submitted_assignment', to:'assignments#submitted_assignment'

  resources :settings
  get 'change_locale', to:'settings#change_locale'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.role == "educator"
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  after_create_commit { notify }
  # belongs_to :subject
  belongs_to :user
  has_many :user_assignments
  mount_uploader :avatar, AvatarUploader

  private

  def notify
    Notification.create(event: "New Assignment")
  end
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :subject
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :subject
  belongs_to :user
end

app/models/donate.rb
class Donate < ApplicationRecord
  belongs_to :user
  enum amount_type: [:complete, :monthly]
  enum CreditCardType: [:Visa, :Maestro ]
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :performance
  belongs_to :user
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :subject
  belongs_to :performance  
end

app/models/help.rb
class Help < ApplicationRecord
  enum user_type: [:student, :educator]
  enum level_type: [:beginner, :intermediate, :advanced]
end

app/models/home.rb
class Home < ApplicationRecord
  def self.search(search)
    where("Title LIKE ? ","%#{search}%")
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  after_create_commit { NotificationBroadcastJob.perform_now(Notification.count)}
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :user
  has_one :course_progress
  has_many :grades
  has_one :feedback
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :subject
  belongs_to :user
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
  has_one :calendar
  has_one :grade
  has_one :course_progress
  has_many :discussions
  mount_uploader :avatar, AvatarUploader
  has_many :ratings

  def self.search(term)
    where("Name LIKE ? ","%#{term}%")
  end

  def average_rating
    ratings.sum(:score) / ratings.size
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # after_initialize :assign_default_role, :if => :new_record?
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2, :twitter]

  mount_uploader :avatar, AvatarUploader
  serialize :avatars, JSON
  has_many :subjects
  has_many :feedbacks
  has_one  :performance
  has_many :grades
  has_many :assignments
  has_many :user_assignments
  has_many :inverse_user_assignments, :class_name => "User", :foreign_key => "educator_id"
  has_many :discussions
  has_many :donates
  has_many :ratings
  has_many :surveys
  has_many :questions
  has_many :comments

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end
    user
  end

  def self.new_with_session(params, session)
   super.tap do |user|
     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
   end
  end

  def assign_default_role
    self.add_role(:learner) if self.roles.blank?
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  load_and_authorize_resource param_method: :sub_params , only: [:new, :create, :index, :update, :show]
  
  def index
    if params[:term]
      @subjects = Subject.search(params[:term])
    else
      @subjects = Subject.all
    end
  end

  def new
    @subject = Subject.new
  end

  def create
    if current_user.subjects.create(sub_params)
      redirect_to subjects_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @subject = Subject.find(params[:id])
    @rating = Rating.where(subject_id: @subject.id, user_id: current_user.id).first
    unless @rating
      @rating = Rating.create(subject_id: @subject.id, user_id: current_user.id, score: 0)
    end
  end

  def about_page
    @subject = Subject.find(params[:id])
  end

  def rate_update
    @rating = Rating.find(params[:id])
    @subject = @rating.subject
    if @rating.update_attributes(score: params[:score])
      respond_to do |format|
        format.js
      end
    end
  end

  def update
  end 

  def educator_courses
    @user = current_user
    @subject = @user.subjects 
  end

  private

  def sub_params
    params.require(:subject).permit(:name, :objective, :lesson_plan, :content, :homepage, :avatar, :avatar_cache, :term)
  end
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/about_page.html.erb
<p>
<h4>Course Description :-</h4>
  <%= @subject.content %>
</p>

<p>
<h4>Course Objective :-</h4>
  <%= @subject.objective %>
</p>

<p>
<h4>Course Lesson/Plan Summary :-</h4>
  <%= @subject.lesson_plan %>
</p>

app/views/subjects/educator_courses.html.erb
<% if @subject.present? %>
  <table>
      <tr>
        <th style="padding:0 15px 0 15px;">image</th>
        <th style="padding:0 15px 0 15px;">name</th>
        <th style="padding:0 15px 0 15px;">objective</th>
        <th style="padding:0 15px 0 15px;">lesson_plan</th>
        <th style="padding:0 15px 0 15px;">content</th>
        <!-- <th colspan="3"></th> -->
      </tr>
     
      <% @subject.each do |subject| %>
        <tr>
          <td style="padding:0 15px 0 15px;"><%=link_to (image_tag subject.avatar, size: "100x100"), subject_path(subject) %></td>
          <td style="padding:0 15px 0 15px;"><%= subject.name %></td>
          <td style="padding:0 15px 0 15px;"><%= subject.objective %></td>
          <td style="padding:0 15px 0 15px;"><%= subject.lesson_plan %></td>
          <td style="padding:0 15px 0 15px;"><%= subject.content %></td>
          
          <td><%#= link_to 'Show', article_path(article) %></td>
          <td><%#= link_to 'Edit', edit_article_path(article) %></td>
          <td><%#= link_to 'Destroy', article_path(article),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>
<% else %>
  <h2> you don't have any created subject </h2>
<% end %>

app/views/subjects/index.html.erb
<div class="text-center">
  <br><%= form_tag(subjects_path, :method => "get") do %>
    <%= text_field_tag :term, params[:term], placeholder: "Search for course you want to learn",:size=>"31x15" %>
    <%= submit_tag "Search", name: nil %>
  <% end %><br /><br />
</div>

<div class="row">
  <% @subjects.each do |subject| %>
      <div class="col-md-3 col-sm-3 col-xs-12">
        <%=link_to (image_tag subject.avatar, size: "200x200"), subject_path(subject) %><br />
            Course Name: <%= subject.name %><br />
            Author Name: <%= current_user.first_name %><%= current_user.last_name %><br /><br /><br />
      </div>
  <% end %> 
</div>
  

app/views/subjects/new.html.erb
<%= form_for @subject do |form| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@subject.errors.count,"error") %> prohibited this subject from being saved:
      </h2>
      <ul>
        <%= @subject.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row equal">

    <div class="col-xs-6 col-sm-3">
      <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
      </p>
      
      <p>
        <%= form.label :objective, "Course Objective" %><br>
        <%= form.text_field :objective %>
      </p>
      
      <p>
        <%= form.label :lesson_plan , "Lesson Plan"%><br>
        <%= form.text_area :lesson_plan %>
      </p>
      
      <p>
        <%= form.label :content, "Course Content" %><br>
        <%= form.text_area :content %>
      </p>
      
      <p>
        <%= form.label :homepage, "Course Homepage" %><br>
        <%= form.text_field :homepage %>
      </p>
    </div>

      <div action="/media-upload" class="dropzone">
        <div class="fallback">
          <%= form.file_field :avatar %>
        </div>
      </div>

    <div class="col-xs-6 col-sm-3">
      <h3>Helpful Tips:-</h3>
      structure your thoughts 
      shorten the time it takes to create your course by making a course by making a course outline
    </div>
  </div>  

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/subjects/show.html.erb
<br><div class="wrapper">
    <button class="button"><%= link_to "About Page", about_page_path(@subject) %></button>&nbsp;&nbsp;
    <button ><%= link_to "assignment/tasks/topics", calendars_path %></button>
</div>


<p>
  <%= image_tag (@subject.avatar), size: "100x100" %>
</p>

<p>
  <%= @subject.name %>
</p>

<p>
  <%= @subject.objective %>
</p>

<p>
  <%= @subject.lesson_plan %>
</p>

<p>
  <%= @subject.content %>
</p>

<p>
  <%= @subject.homepage %>
</p>

<%#= link_to "give rating", subject_rating_path(@subject.id, @rating.id)%>

<p>Averate rating</p>
<div id="star"></div>
<!-- <p>Your rating</p>
<div id="user_star"></div> -->



<script type="text/javascript">
$(document).ready(function(){
  $('#star').raty({
    readOnly: false,
    score: <%= @subject.average_rating %>,
    path: '/assets'
  });
  // $('#user_star').raty({
  //   score: <%= @rating.score %>,
  //   path: '/assets',
  //   click: function(score, evt) {
  //     debugger
  //     $.ajax({
  //       url: '/ratings/' + <%= @rating.id %>,
  //       type: 'PATCH',
  //       data: { score: score }
  //     }).done(function (data){
  //       debugger
  //     });
  //   }
  // });
});
</script>

<style type="text/css">
.wrapper {
    text-align: center;
}

.button {
    /*position: absolute;*/
    /*top: 50%;*/
}
</style>